spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port = 8080

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

# ===============================
# JPA / HIBERNATE
# ===============================
 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.current_session_context_class.1=org.springframework.orm.hibernate5.SpringSessionContext

spring.main.allow-bean-definition-overriding=true

hostDomainUrl = http://169.38.132.167:4234/
bnapi_key=6edfe7d5-c527-4998-bed6-7f7286a0e0e9

#Developement
#admin_name = Moneyflow Investments 
#admin_mobile = 9988845111
#admin_email = ajith@advisorkhoj.com
#support_name = Moneyflow Investments 
#support_email = ajith@advisorkhoj.com
#mail_support_name = Moneyflow Investments 
#mail_support_email = ajith@advisorkhoj.com


#Production
admin_name = Myassetz
admin_mobile = 9988845111
admin_email = kathir144120@gmail.com
support_name = Myassetz
support_email = kathir144120@gmail.com
mail_support_name = Myassetz
mail_support_email = kathir144120@gmail.com

api_key = 252e3780-93ec-4254-beaa-f21f5af2dbc9