package com.credible.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PostNeed generated by hbm2java
 */
@Entity
@Table(name = "post_queries")
public class PostQueries implements java.io.Serializable {

	public static final int OPEN = 1;
	public static final int CLOSE = 2;
	public static final int CANCEL = 3;
	public static final int WAITED = 4;
	private int id;
	private String name;
	private String email;
	private String mobile;
	private String city;
	private String area;
	private String description;
	private int status;
	private Date created_on;
	private String cancel_reason;
	private Integer email_query;
	private Integer download_query;
	private String source;
	private String client_name;
	
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getArea() {
		return area;
	}
	public void setArea(String area) {
		this.area = area;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public Date getCreated_on() {
		return created_on;
	}
	public void setCreated_on(Date created_on) {
		this.created_on = created_on;
	}
	public String getCancel_reason() {
		return cancel_reason;
	}
	public void setCancel_reason(String cancel_reason) {
		this.cancel_reason = cancel_reason;
	}
	public static int getOpen() {
		return OPEN;
	}
	public static int getClose() {
		return CLOSE;
	}
	public static int getCancel() {
		return CANCEL;
	}
	public static int getWaited() {
		return WAITED;
	}
	public Integer getEmail_query() {
		return email_query;
	}
	public void setEmail_query(Integer email_query) {
		this.email_query = email_query;
	}
	public Integer getDownload_query() {
		return download_query;
	}
	public void setDownload_query(Integer download_query) {
		this.download_query = download_query;
	}
	public String getSource() {
		return source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public String getClient_name() {
		return client_name;
	}
	public void setClient_name(String client_name) {
		this.client_name = client_name;
	}
}
